/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class touchatag_Touchatag */

#ifndef _Included_touchatag_Touchatag
#define _Included_touchatag_Touchatag
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     touchatag_Touchatag
 * Method:    nativeTagID
 * Signature: ()[[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_touchatag_Touchatag_nativeTagID
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     touchatag_Touchatag
 * Method:    nativeConnectedRFID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_touchatag_Touchatag_nativeConnectedRFID
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
